name: watchlist
description: "A bookmark/watchlist app with parallax depth cards."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Networking & Images
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.1
  http: ^1.1.0
  
  # Sensors for parallax
  sensors_plus: ^4.0.2
  
  # Import/Export
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
